version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: staging_layer

    tables:
      - name: stg_customerdata
      - name: stg_payments
      - name: stg_order
